name: Portfolio Report

on:
  workflow_dispatch:
  schedule:
    - cron: "00 3-10 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas numpy yfinance

    - name: Run report script
      run: |
        rm -rf output/portfolio/
        mkdir -p output
        sh scripts/portfolio.sh

    - name: Prepare GitHub Pages
      run: |
        mkdir public
        cp output/portfolio/portfolio_report.csv public/
        cp web/index.html public/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
